# Generated by Django 5.2.8 on 2025-11-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_staycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staycontact',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
